name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/tronikos/opower.git
          git fetch upstream

      - name: Sync with upstream
        run: |
          git checkout main
          git merge -X theirs upstream/main
          git push origin main

      - name: Delete unneeded workflows
        run: |
          rm -f .github/workflows/python-package.yml
          rm -f .github/workflows/python-publish.yml

      - name: Commit changes
        run: |
          git add .
          git commit -m "Delete unneeded workflow files"
          git push origin main